# Generated by Django 2.1.1 on 2018-12-02 10:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_register', models.DateField(blank=True, null=True, verbose_name='Registered')),
                ('email_address', models.EmailField(max_length=254)),
                ('no_of_blog_posts', models.IntegerField()),
                ('no_of_shares', models.IntegerField()),
                ('no_of_likes', models.IntegerField()),
                ('no_of_dislikes', models.IntegerField()),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='BlogInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular blog across all Blogs', primary_key=True, serialize=False)),
                ('comment_ornot', models.BooleanField(null=True)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['post_date'],
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Please write your blog content here.., maximum 10000 words', max_length=10000)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('comments', models.TextField(max_length=1000)),
                ('comment_count', models.IntegerField()),
                ('comment_ornot', models.BooleanField(null=True)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('shared', models.BooleanField(null=True)),
                ('shared_freq', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hariblog.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book theme (e.g. Agriculture Policy, Food Security)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='theme',
            field=models.ManyToManyField(help_text='Select a theme for this post', to='hariblog.Theme'),
        ),
        migrations.AddField(
            model_name='bloginstance',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hariblog.Blogs'),
        ),
    ]
