# Generated by Django 2.1.1 on 2018-12-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hariblog', '0002_auto_20181202_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='no_of_blog_posts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='no_of_dislikes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='no_of_likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='no_of_shares',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='dislikes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='shared_freq',
            field=models.IntegerField(null=True),
        ),
    ]
