# Generated by Django 2.1.1 on 2018-12-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hariblog', '0003_auto_20181202_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='no_of_blog_posts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='no_of_dislikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='no_of_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='no_of_shares',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
