# Generated by Django 2.1.1 on 2018-12-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hariblog', '0006_auto_20181202_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='no_of_dislikes',
        ),
        migrations.RemoveField(
            model_name='author',
            name='no_of_likes',
        ),
        migrations.RemoveField(
            model_name='author',
            name='no_of_shares',
        ),
        migrations.AddField(
            model_name='bloginstance',
            name='no_of_dislikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloginstance',
            name='no_of_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloginstance',
            name='no_of_shares',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
