# Generated by Django 2.1.1 on 2018-12-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hariblog', '0007_auto_20181202_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloginstance',
            name='no_of_likes',
        ),
        migrations.AlterField(
            model_name='bloginstance',
            name='post_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
